name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: ${{ vars.MIRROR_URL }}

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check coding style
        run: |
          check.sh $(pwd) $(pwd) ; exit_status=$?
          if [ -f coding-style-reports.log ] && [ -s coding-style-reports.log ]; then
            while read -r line; do
              file=$(echo "$line" | cut -d ':' -f 1)
              line_number=$(echo "$line" | cut -d ':' -f 2)
              error_message=$(echo "$line" | cut -d ':' -f 3-)
              path="$GITHUB_WORKSPACE/$file"
              echo "::error file=$path,line=$line_number:: $error_message"
            done < coding-style-reports.log
            exit 1
          elif [ $exit_status -ne 0 ]; then
            echo "check.sh failed with exit status $exit_status"
            exit $exit_status
          fi
          exit 0
        
  push_to_mirror:
    needs: check_coding_style
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          echo "${{ secrets.EPITECH_TOKEN }}" > private_key.pem
          chmod 600 private_key.pem
          ssh-keyscan -t rsa -H "$(echo "${{ env.MIRROR_URL }}" | awk -F@ '{print $2}' | awk -F/ '{print $1}' | awk -F: '{print $1}')" >> known_hosts
          export GIT_SSH_COMMAND="ssh -i private_key.pem -o UserKnownHostsFile=known_hosts"

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@main
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.EPITECH_TOKEN }}
